model: models\V11_SPDH.yaml

training:
  imgsz: 640
  batch: 8
  epochs: 300
  optimizer: ADAMW
  lr0: 0.001
  mosaic: 0
  close_mosaic: 20
  patience: 100
  workers: 2
  amp: True
  cos_lr: True #false for linear lr scheduler, true for cosine lr scheduler, BAsline YOLOv11 uses cosine lr scheduler, but YOLOv8 uses linear lr scheduler
  warmup_epochs: 5
    


experiment:
  name: NEUDET_v11n+SPDHybrid_NEW_ADAMW__300epochs
  seeds: [1]
  project_dir: runs/detect/experiments

data:
  config: configs/data.yaml