model: models\V2_DK_SPDHY_yolo11.yaml

training:
  imgsz: 640
  batch: 8
  epochs: 220
  optimizer: AdamW
  lr0: 0.001
  mosaic: 0
  close_mosaic: 20
  patience: 30
  workers: 2
  amp: true
  cos_lr: True #false for linear lr scheduler, true for cosine lr scheduler, BAsline YOLOv11 uses cosine lr scheduler, but YOLOv8 uses linear lr scheduler
  warmup_epochs: 5
    


experiment:
  name: GC10_Baseline_YOLO_v11n_640px_AdamW__220epochs
  seeds: [1]
  project_dir: runs/detect/experiments

data:
  config: configs/data.yaml